runtime: custom
env: flex

env_variables:
  RAILS_ENV: production
  RAILS_MASTER_KEY: 0308c1e690525cb29bf2e87721744ecb
  SUPABASE_DATABASE_URL: "postgresql://postgres:%40Thebestboy10@postgres.gifbdzhmvjwengppexle.supabase.co:6543/postgres"

manual_scaling:
  instances: 1
